language: ruby
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - bundle exec rake db:reset
  - bundle exec rake db:setup
  - bundle exec rake cgap:db:migrate
script:
  - bundle exec rspec
  - bundle exec rake test